[tool.poetry]
name = "flowter"
version = "0.2.0"
description = "ğŸŒŠ Flowter: Making your Python pipelines glide as effortlessly as an otter in water. ğŸ¦¦"
authors = ["Allen Chou <f1470891079@gmail.com>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.0,<3.12.0"
rich = "*"
pytz = "*"
typing-extensions = "*"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
toml = "^0.10.2"
isort = "^5.12.0"
black = "^23.10.0"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.4.6"

[tool.poetry.extras]
dev = ["pytest"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
